### ISSUE TITLE
problem about weights loading

### ISSUE THREAD

**Issue by zhangyu13a** [sinamalakouti/CDDMSL#1]
Thanks for your great work! But there are still some problems I dont unstand. 
There is 'p = self.cfg.MODEL.PRE_TRAINED_RCLIP_PATH' in train_loop.py, so what PRE_TRAINED_RCLIP_PATH is? Does it refers to 'MODEL.WEIGHTS' in faster_rcnn_city.sh?

**Comment by sinamalakouti** [comment]
Hi @zhangyu13a, 
Thank you so much! And sorry for the confusion. 

No,  `MODEL.PRE_TRAINED_RCLIP_PATH ` is used to set the offline_backbone in the regionCLIP model. I used this only for the Knowledge Distillation loss (i.e. offline_backbone would be the green encoder in Fig. 2 of the paper). Note that at the beginning of the training, the Main visual encoder/backbone (i.e., what we train) and offline_backbone have the same weights. However, they will be different after training starts.

Please let me know if you have more questions!

**Comment by zhangyu13a** [comment]
Got it! Thank you for your prompt reply！
